### ISSUE TITLE
Alpha channel change to black in Gaussian Blur

### ISSUE THREAD

**Issue by zijing07** [ragnraok/android-image-filter#17]
When I apply Gaussian Blur to a bitmap with alpha channel, the alpha channel changes to black. While the alpha channel is good if I use RenderScript. Is it possible to keep the alpha channel in the filtering process?

**Comment by ragnraok** [comment]
sorry, the GaussianBlurFilter current implementation is ignore alpha channel in the pixel, you can fix this by modify [GaussianBlurFilter.cpp](https://github.com/ragnraok/android-image-filter/blob/ff2f0348d6e239d22f30ef2a3c57be6277d74428/library/jni/GaussianBlurFilter.cpp), re-add the alpha channel data in the output buffer:


```C++
	for (int row = bound; row < height - bound; row++) {
		for (int col = bound; col < width - bound; col++) {
			index = 0;
			Color pixColor(tempPixels[row * width + col]);
			sumR = sumG = sumB = 0;
			for (int i = -bound; i <= bound; i++) {
				for (int j = -bound; j <= bound; j++) {
					int pixel_index = (row + i) * width + col + j;
					if (pixel_index < width * height) {
						Color color(tempPixels[pixel_index]);
						sumR += color.R() * kernel[index];
						sumG += color.G() * kernel[index];
						sumB += color.B() * kernel[index];
						index++;
					}

				}
			}

			pixels[row * width + col] = ARGB2Color(pixColor.alpha(), int(sumR), int(sumG), int(sumB));
		}
	}
```
