### ISSUE TITLE
filters leave a small border around an image untouched

### ISSUE THREAD

**Issue by pigovsky** [ragnraok/android-image-filter#21]
Dear RagnarokStack,

I have used your library android-image-filter. It is very helpful and good implemented. Thanks a lot!

But filters leave a small border around an image untouched, how to solve this problem?

Sincerely,
Y.P.

**Comment by ragnraok** [comment]
can you post a picture to show the problem?

**Comment by pigovsky** [comment]
Original:
![original](https://cloud.githubusercontent.com/assets/5992062/21479066/2d3310ae-cb5a-11e6-9935-4dff3d2726c3.png)


Gaussian-blurred:
![gaussianblur](https://cloud.githubusercontent.com/assets/5992062/21479045/15dc2896-cb5a-11e6-91cd-c6686b6f869b.png)

**Comment by ragnraok** [comment]
It looks weird, what's the size of picture? and can you post your code?

**Comment by pigovsky** [comment]
https://github.com/pigovsky/android-image-filter/tree/b_scale_blur_coefficient

**Comment by ragnraok** [comment]
can you create a pull request?

**Comment by pigovsky** [comment]
are you going to pull my `b_scale_blur_coefficient` branch into your project?

**Comment by ragnraok** [comment]
If you branch fixed this issue, I hope you can create a pull request, thx
